# Document:
# http://simiki.org/docs/configuration.html

url: http://blog.heyunfan.com/wiki/
title: 何云帆的wiki
keywords: wiki,simiki
description: newpage of github
author: heyunfan
theme: yasimple_x2
root: /wiki/