# Document:
# http://simiki.org/docs/configuration.html

url: wiki.heyunfan.me
title: 何先生的wiki
keywords: wiki,simiki
description: newpage of github
author: heyunfan
theme: simple
default_ext: md
pygments: true
debug: false
